spring:
  datasource:
    url: jdbc:mysql://localhost/wis-new?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: rdc2006
    driver-class-name: com.mysql.jdbc.Driver
logging:
  path: D:/logs
  level: info
