server:
  port: 8080
  tomcat:
    uri-encoding: UTF-8
spring:
  profiles:
    active: dev
  thymeleaf:
    cache: false
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  http:
    encoding: 
      charset: UTF-8
      force:  true
      enabled:  true
mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.temp.common.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
logging:
  config: classpath:config/logback-spring.xml
tx:
  wx: false
  dx: false
  yj: false
